server:
  port: 8080
  mode: debug  # debug, release
  domain: lanxin168.com

database:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: "LanXin@2024MySQL"
    database: lanxin_im
    charset: utf8mb4
    max_idle_conns: 10
    max_open_conns: 100
    log_mode: true

redis:
  host: localhost
  port: 6379
  password: ""  # 请设置环境变量 REDIS_PASSWORD
  db: 0
  pool_size: 10

kafka:
  brokers:
    - localhost:9092
  topic:
    message: lanxin_message
    notification: lanxin_notification

jwt:
  secret: ""  # 请设置环境变量 JWT_SECRET
  expire_hours: 24
  refresh_expire_hours: 168

storage:
  cos:
    secret_id: ""  # 自建COS访问密钥ID
    secret_key: ""  # 自建COS访问密钥
    bucket: lanxin-files
    region: default
    base_url: http://localhost:9000  # 自建COS服务地址（例如MinIO）
  
trtc:
  sdk_app_id: 1600109367  # 腾讯云TRTC应用ID
  secret_key: "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgZeevqkdnxJKQyLbnjUm3YX8dNTPdzTp6gCCGl1B5V7OhRANCAATaOYqPzlXTTVBk+O4o/AQYMuBi3quZuGNAazQuICmGIzwET508Dvw09RTQFZwPiJ8VGInKDnzUotHo5sJ+FfmC"  # 腾讯云TRTC密钥（私钥）
  expire_time: 86400

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  heartbeat_interval: 30
  max_message_size: 10240

security:
  bcrypt_cost: 12
  rate_limit:
    enabled: true
    requests_per_minute: 60
  cors:
    allowed_origins:
      - http://localhost:3000
      - https://admin.lanxin168.com
      - http://154.40.45.121:5173
      - http://154.40.45.121:3000
    allowed_methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed_headers:
      - Authorization
      - Content-Type

